# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:127.0.0.1" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

copyright: dambaev alexander, theice@inbox.ru (c) 2015 
#analytics: UA-YOURCODE

status-cmd: /opt/pppwebui/bin/status
restart-cmd: /opt/pppwebui/bin/restart
secret-file: /etc/ppp/chap-secrets
pam-service: other
acl-status: acl_pppwebui_status
acl-restart: acl_pppwebui_restart
acl-settings-r: acl_pppwebui_settings_r
acl-settings-w: acl_pppwebui_settings_w
syslog-id: pppwebui


